server:
  port: 8080
  servlet:
    context-path: /walk/
#spring:   // memory db
#  datasource:
#    url: jdbc:h2:file:~/h2data;AUTO_SERVER=TRUE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

# local mysql test db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/walk?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2.console.enabled: true
  jpa:
    show-sql: true
    hibernate:
      # create로 설정하면 실행 시, 기존 테이블을 삭제하고 새로 생성하게 됨.
      ddl-auto: create
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace



