server:
  port: 8080
  servlet:
    context-path: /walk/
#spring:   // memory db
#  datasource:
#    url: jdbc:h2:file:~/h2data;AUTO_SERVER=TRUE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

# local mysql test db
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/walk?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2.console.enabled: true
  jpa:
    show-sql: true
    hibernate:
      # create로 설정하면 실행 시, 기존 테이블을 삭제하고 새로 생성하게 됨.
      # 실수로 운영에 반영하면 짤리거나 별명이 드랍더테이블로 바뀐다.
      ddl-auto: validate
      #ddl-auto: update
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace




