server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:file:~/h2data;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2.console.enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.type: trace